### ISSUE TITLE
求资源

### ISSUE THREAD

**Issue by pengyang0317** [yuejin66/emos#1]
您好！  
可以把 docker的  face.tar.gz 文件， 和demo.tar 文件也上次到您这git上吗

**Comment by yuejin66** [comment]
链接：https://pan.baidu.com/s/1cwHpMzr34JoiYRTj6hxLNQ 
提取码：1234

**Comment by pengyang0317** [comment]
&nbsp;收到了， 非常感谢您！&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuejin66/emos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月10日(星期六) 晚上10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuejin66/emos] 求资源 (#1)





 
链接：https://pan.baidu.com/s/1cwHpMzr34JoiYRTj6hxLNQ
 提取码：1234

**Comment by linxiaoyan01** [comment]
链接失效了，可以再传一遍吗

**Comment by kikhot** [comment]
您好！这个链接可以更新一下吗，非常感谢
